---
# file: roles/ansible/tasks/main.yml
- name: Install software-properties-common
  apt: name=software-properties-common

- name: add ansible stable repository from PPA and install its signing key.
  apt_repository: repo='ppa:ansible/ansible' update_cache=yes

- name: Install ansible
  apt: name=ansible state=latest

- name: Install python package.
  pip: name={{ item }} state=present
  with_items:
    - pywinrm
    - azure
    - docker-py
    - docker-compose