---
# file: roles/nodejs/tasks/main.yml
- name: Download setup shell for node.js v7
  get_url: url="https://deb.nodesource.com/setup_7.x" dest="/tmp/setup_node.sh"

- name: Setup node.js
  shell: sh /tmp/setup_node.sh

- name: Install node.js
  apt: name=nodejs state=latest

- name: Install build-essential
  apt: name=build-essential state=present
